# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eJ8MeY1w5LT4n5Yz3zUwKleUhX3EuQol
"""

import pandas as pd
import os
from pathlib import Path

def search_ingredients(subs , n_rec):
  #print(os.getcwd())
  #x = Path('./')
  #print(list(filter(lambda y:y.is_file(), x.iterdir())))
  
    
  df= pd.read_csv("https://storage.googleapis.com/us-east1-airflowenv-ce25265b-bucket/dags/df_parsed.csv")
  df2=pd.DataFrame()
  #print(df.head())
  #subs = ["chicken" , "onion" , "tomato"]
  n = len(subs)
  for i in range(0,n):
    #dct['lst'+str(i)] = df['ingredients_parsed'].str.contains(subs[i]).values.tolist()
    df2["Ingredient"+str(i)]= df['ingredients_parsed'].str.contains(subs[i]).values.tolist()
  #print(df2)


  #df2

  countlist=[]
  for row in range(0,4647):
    c=0
    #print(row)
    for i in range(0,n):
      #print(df2.iloc[row][i])
      if (str(df2.iloc[row][i]))=="True":
        c=c+1
        #print("True")
    #print(c)
    #break
    countlist.append(c)
  #print(countlist)

  #print(countlist)

  df2["count"]=countlist
  #df2

  df3=df2.sort_values(by='count', ascending=False)
  #df3

  index = df3.index
  indices = index[df3["count"] >0] 

  indices_list = indices.tolist()
  #print(indices_list)

  
  final_indeces = indices_list[0:n_rec] #n recommendations

  final_df = df.iloc[final_indeces]

  final_df = final_df.iloc[:,:3]
  print("Sending dataframe---------------------------->")
  return final_df


def search_collections(collection):
  #print(os.getcwd())
  #x = Path('./')
  #print(list(filter(lambda y:y.is_file(), x.iterdir())))
  df_2= pd.read_csv("https://storage.googleapis.com/us-east1-airflowenv-ce25265b-bucket/dags/df_parsed.csv")
  df2_2=pd.DataFrame()
  
  if collection == "Seafood":
    df2_2 = df_2[df_2['recipe_urls'].str.contains("seafood")==True]

  if collection == "Soup":
    df2_2 = df_2[df_2['recipe_urls'].str.contains("soup")==True]

  if collection == "Curry":
    df2_2 = df_2[df_2['recipe_urls'].str.contains("curry")==True]

  if collection == "Pasta":
    df2_2 = df_2[df_2['recipe_urls'].str.contains("pasta")==True]

  if collection == "Salad":
    df2_2 = df_2[df_2['recipe_urls'].str.contains("salad")==True]

  if collection == "Chinese":
    df2_2 = df_2[df_2['recipe_urls'].str.contains("chinese")==True]
  #print(df2_2)


  print("Sending collections---------------------------->")
  return df2_2.iloc[:,:3]

